# Cargo will automatically use the optimal number of jobs

[net]
# Use multiple Git connections for faster dependency downloads
git-fetch-with-cli = true

[profile.dev]
# Optimize compilation speed
codegen-units = 16
incremental = true

[profile.dev.package."*"]
# Don't optimize dependencies during development
opt-level = 0 

 